name: Example Runs Testing

on:
  push:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: fetch-latest-github-release
        uses: ./

      - name: print out latest release tag
        run: echo "The latest release tag is $TAG"
        env:
          TAG: ${{ steps.fetch-latest-github-release.outputs.tag_name }}
  customRepoExample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: fetch-latest-github-release
        uses: ./
        with:
          github_token: ${{ github.token }}
          repo_path: actions/runner

      - name: print out latest release tag
        run: echo "The latest release tag is $TAG"
        env:
          TAG: ${{ steps.fetch-latest-github-release.outputs.tag_name }}


