# This workflow runs the tests for the application and comments the coverage report to the pull requests that was open.
# It uses the Action described here https://github.com/marketplace/actions/jest-annotations-coverage.

name: Tests Coverage
on: pull_request
jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Respository
        uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
            node-version: '16'
      - name: Run Jest Test Coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}